apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer